import { FortuneCategory } from '@/types';
import { Locale } from './i18n/translations';

// 점수 구간 (5점 단위)
export type ScoreRange =
  | '95-100' | '90-94' | '85-89' | '80-84' | '75-79'
  | '70-74' | '65-69' | '60-64' | '55-59' | '50-54'
  | '45-49' | '40-44' | '35-39' | '30-34' | '25-29'
  | '20-24' | '15-19' | '10-14' | '5-9' | '0-4';

export function getScoreRange(score: number): ScoreRange {
  if (score >= 95) return '95-100';
  if (score >= 90) return '90-94';
  if (score >= 85) return '85-89';
  if (score >= 80) return '80-84';
  if (score >= 75) return '75-79';
  if (score >= 70) return '70-74';
  if (score >= 65) return '65-69';
  if (score >= 60) return '60-64';
  if (score >= 55) return '55-59';
  if (score >= 50) return '50-54';
  if (score >= 45) return '45-49';
  if (score >= 40) return '40-44';
  if (score >= 35) return '35-39';
  if (score >= 30) return '30-34';
  if (score >= 25) return '25-29';
  if (score >= 20) return '20-24';
  if (score >= 15) return '15-19';
  if (score >= 10) return '10-14';
  if (score >= 5) return '5-9';
  return '0-4';
}

// 카테고리별, 점수 구간별 설명
export const categoryDescriptions: Record<Locale, Record<FortuneCategory, Record<ScoreRange, string>>> = {
  en: {
    love: {
      '95-100': "Your romantic energy is absolutely radiant today! The universe has aligned perfectly for matters of the heart. A destined encounter or a deeply meaningful moment with your loved one awaits. This is a once-in-a-lifetime opportunity for love. Every conversation sparkles with connection, and your charm is irresistible. Trust your heart completely—it knows exactly where to lead you.",
      '90-94': "Your romantic energy is absolutely radiant today! The universe has aligned perfectly for matters of the heart. A destined encounter or a deeply meaningful moment with your loved one awaits. Every conversation sparkles with connection, and your charm is irresistible. Trust your heart completely—it knows exactly where to lead you.",
      '85-89': "Love flows naturally toward you today. Your emotional intuition is heightened, making it easy to connect with others on a deeper level. If you're in a relationship, expect warm and meaningful exchanges. Singles may find themselves drawn to someone special.",
      '80-84': "Love flows naturally toward you today. Your emotional intuition is heightened, making it easy to connect with others. If you're in a relationship, expect warm exchanges. Singles may find interesting conversations ahead.",
      '75-79': "A gentle romantic energy surrounds you today. While not explosive, there's a steady warmth in your love life. Small gestures of affection will be noticed and appreciated. Be open to subtle signs of interest.",
      '70-74': "A gentle romantic energy surrounds you today. There's a steady warmth in your connections. Small gestures of affection will be noticed. Stay receptive to those around you.",
      '65-69': "Your love life maintains a comfortable balance today. Nothing dramatic, but pleasant interactions are likely. Focus on appreciating what you have rather than seeking excitement.",
      '60-64': "Your love life maintains a comfortable balance today. Pleasant interactions are possible. Focus on appreciating the small moments and being present with loved ones.",
      '55-59': "Romance takes a quieter tone today. Don't force connections—let things unfold naturally. It's a good day for self-reflection about what you truly want in relationships.",
      '50-54': "Romance takes a quieter tone today. Don't force connections. Use this time for self-reflection about your relationship goals and emotional needs.",
      '45-49': "You may feel some emotional distance today. Communication might require extra effort. Be patient with yourself and others—not every day needs to be romantic.",
      '40-44': "You may feel some emotional distance today. Communication requires extra effort. Be patient and avoid pushing for deep conversations. Some misunderstandings are possible.",
      '35-39': "Romantic energies are subdued today. You might feel misunderstood or overlooked. Take a step back from relationship pressures and focus on your own emotional well-being.",
      '30-34': "Romantic energies are subdued today. You might feel misunderstood or overlooked. Avoid making important relationship decisions. Some tension in interactions is possible.",
      '25-29': "Today may bring some challenges in love. Miscommunications or feelings of disconnect are likely. It's best to postpone serious relationship talks and focus on self-care.",
      '20-24': "Today may bring challenges in love. Miscommunications or feelings of disconnect are likely. Avoid confrontations. Past issues might resurface unexpectedly.",
      '15-19': "A difficult day for romantic matters. Emotions may feel heavy, and connections strained. Protect your heart and avoid making any permanent decisions about relationships.",
      '10-14': "A difficult day for romantic matters. Emotions feel heavy and connections strained. Arguments or disappointments are possible. Give yourself space to process feelings.",
      '5-9': "Love feels distant and challenging today. You may experience rejection or deep misunderstanding. This is a day for emotional protection, not pursuit. Better days are coming.",
      '0-4': "Love feels very distant today. You may experience rejection or deep misunderstanding. Isolation might feel necessary. This is a day for emotional protection only. Remember, this too shall pass.",
    },
    money: {
      '95-100': "Financial fortune shines brilliantly upon you today! The stars indicate exceptional opportunities for wealth and prosperity. A major breakthrough in income or an unexpected windfall is highly likely. Your financial instincts are razor-sharp—trust them completely. This is the perfect day to make bold financial moves. Every investment decision you make today is blessed with cosmic luck.",
      '90-94': "Financial fortune shines brilliantly upon you today! The stars indicate exceptional opportunities for wealth and prosperity. A major breakthrough in income or an unexpected windfall is highly likely. Your financial instincts are razor-sharp—trust them completely. Every investment decision you make today is blessed.",
      '85-89': "Money matters look very favorable today. Your judgment about finances is sound, and opportunities for gain are present. Whether it's a raise, a good deal, or smart savings, prosperity flows your way.",
      '80-84': "Money matters look favorable today. Your judgment about finances is sound, and opportunities for gain are present. A good deal or smart savings opportunity may appear.",
      '75-79': "A stable and positive day for finances. Small gains are possible, and your spending decisions are likely to be wise. Not a day for huge risks, but steady progress is yours.",
      '70-74': "A stable day for finances. Small gains are possible, and your spending decisions are likely wise. Focus on steady progress rather than big risks.",
      '65-69': "Your financial situation remains balanced today. No major gains or losses expected—a good day for routine money management and planning for the future.",
      '60-64': "Your financial situation remains balanced today. A good day for routine money management. Review your budget and consider small adjustments.",
      '55-59': "Finances require a bit more attention today. Avoid impulse purchases and stick to your budget. It's not a bad day, just one that rewards caution.",
      '50-54': "Finances require attention today. Avoid impulse purchases and stick to your budget. Review recent expenses and plan for upcoming obligations.",
      '45-49': "Be mindful of your spending today. Unexpected expenses might pop up. Keep some reserves and avoid lending money or making major purchases.",
      '40-44': "Be mindful of spending today. Unexpected expenses might pop up. Keep reserves available and avoid lending money. Some financial stress is possible.",
      '35-39': "Financial caution is advised today. The energy doesn't support new investments or big purchases. Focus on preserving what you have rather than growing it.",
      '30-34': "Financial caution is strongly advised today. The energy doesn't support new investments. Unexpected bills or losses are possible. Focus on preservation.",
      '25-29': "A challenging day for money matters. Delays in payments or unexpected costs may arise. Avoid financial commitments and keep a close eye on your accounts.",
      '20-24': "A challenging day for money matters. Delays in payments or unexpected costs may arise. Financial anxiety might increase. Avoid all unnecessary spending.",
      '15-19': "Financial difficulties may feel pressing today. This is not the time for any monetary risks. Protect your resources and seek advice if needed.",
      '10-14': "Financial difficulties may feel pressing today. Loss or setback is possible. Protect your resources carefully. Seek professional advice if facing major decisions.",
      '5-9': "A very difficult day for finances. Losses or significant setbacks are possible. Avoid all financial decisions if you can. Focus on damage control.",
      '0-4': "A very difficult day for finances. Significant losses or setbacks are possible. Avoid all financial decisions. This is a day for damage control only. Seek support from trusted advisors.",
    },
    study: {
      '95-100': "Your intellectual powers are at their absolute peak today! Knowledge flows into your mind effortlessly, and complex concepts become crystal clear. Exams or academic challenges will feel almost too easy. This is a legendary day for learning. Your memory retention is extraordinary, and creative insights come in waves. Seize this rare opportunity for academic excellence!",
      '90-94': "Your intellectual powers are at their absolute peak today! Knowledge flows into your mind effortlessly, and complex concepts become crystal clear. Exams or academic challenges will feel manageable. Your memory retention is extraordinary, and creative insights come naturally.",
      '85-89': "An excellent day for studying and mental work. Your concentration is strong, and you'll retain information well. Tests, presentations, or important projects have favorable outcomes. Trust your preparation.",
      '80-84': "An excellent day for studying and mental work. Your concentration is strong, and you'll retain information well. Approach academic tasks with confidence.",
      '75-79': "Learning comes smoothly today. You'll find it easier than usual to focus and understand new material. A good day for tackling subjects you've been avoiding.",
      '70-74': "Learning comes smoothly today. You'll find it easier to focus and understand new material. Steady progress on your academic goals is likely.",
      '65-69': "A steady day for academic pursuits. While not exceptional, your efforts will yield proportional results. Consistent work today builds tomorrow's success.",
      '60-64': "A steady day for academic pursuits. Your efforts will yield proportional results. Focus on review and consolidation rather than new material.",
      '55-59': "Studies may require extra effort today. Distractions are more likely, so create a focused environment. Short, concentrated study sessions work better than long ones.",
      '50-54': "Studies may require extra effort today. Distractions are more likely. Keep study sessions short and take regular breaks to maintain effectiveness.",
      '45-49': "Concentration might be challenging today. Don't schedule important exams if possible. Focus on lighter review rather than tackling difficult new concepts.",
      '40-44': "Concentration might be challenging today. Avoid scheduling important exams. Frustration with difficult material is likely. Focus on easier tasks.",
      '35-39': "Academic energy is low today. Learning new things will feel like an uphill battle. If possible, give yourself a lighter study load and rest your mind.",
      '30-34': "Academic energy is low today. Learning feels like an uphill battle. Mental fatigue is likely. Consider postponing challenging intellectual work.",
      '25-29': "A difficult day for intellectual pursuits. Your mind may feel foggy or scattered. Avoid important tests or presentations. Focus on rest and mental recovery.",
      '20-24': "A difficult day for intellectual pursuits. Your mind feels foggy or scattered. Mistakes in work are more likely. Double-check everything important.",
      '15-19': "Mental clarity is significantly impaired today. Studying will feel frustrating and unproductive. Take a break from academics if possible and return refreshed.",
      '10-14': "Mental clarity is significantly impaired today. Studying feels frustrating and unproductive. Errors and forgetfulness are likely. Rest your mind.",
      '5-9': "A very challenging day for learning. Your mind resists focus, and retention is minimal. This is a day for complete mental rest, not academic achievement.",
      '0-4': "A very challenging day for learning. Your mind strongly resists focus, and retention is minimal. Exhaustion or confusion may dominate. Complete rest is essential. Better days for study will come.",
    },
    social: {
      '95-100': "Your social magnetism is absolutely extraordinary today! People are drawn to you like never before, and every interaction sparkles with positive energy. Networking opportunities could change your life. This is a once-in-a-lifetime day for connections. New friendships formed today may last forever. You have the power to inspire and unite everyone around you!",
      '90-94': "Your social magnetism is absolutely extraordinary today! People are drawn to you, and every interaction sparkles with positive energy. Networking opportunities are abundant. New friendships formed today may last a long time. You have the power to inspire those around you.",
      '85-89': "Social interactions flow beautifully today. Your communication skills are enhanced, and others respond warmly to your presence. Great day for team projects, meetings, or making new friends.",
      '80-84': "Social interactions flow beautifully today. Your communication skills are enhanced, and others respond warmly. A good day for team projects or expanding your network.",
      '75-79': "Connections with others come easily today. You'll find common ground quickly and conversations feel natural. Support from friends or colleagues is readily available.",
      '70-74': "Connections with others come easily today. Conversations feel natural, and you'll find common ground. Reach out to someone you've been meaning to contact.",
      '65-69': "A pleasant day for social matters. While not exceptional, interactions will be smooth and cooperative. Maintain your existing relationships with small gestures.",
      '60-64': "A pleasant day for social matters. Interactions will be smooth enough. Focus on maintaining existing relationships rather than building new ones.",
      '55-59': "Social energy is moderate today. Some interactions may require more effort than usual. Choose your social engagements wisely and don't overcommit.",
      '50-54': "Social energy is moderate today. Some interactions require more effort. Be selective about social engagements and preserve energy for important ones.",
      '45-49': "Social situations might feel slightly awkward today. Minor misunderstandings are possible. Be clear in your communication and patient with others.",
      '40-44': "Social situations might feel awkward today. Minor misunderstandings are possible. Avoid group conflicts. Be extra clear in your communication.",
      '35-39': "Interpersonal tensions may arise today. Others might seem less receptive or more critical. Avoid sensitive topics and keep interactions light when possible.",
      '30-34': "Interpersonal tensions may arise today. Others seem less receptive or more critical. Disagreements are likely. Keep discussions light and avoid debates.",
      '25-29': "A challenging day for relationships. Conflicts or feelings of isolation are possible. Limit social engagements and focus on trusted, supportive connections only.",
      '20-24': "A challenging day for relationships. Conflicts or feelings of isolation are likely. You may feel excluded or misunderstood. Limit social exposure.",
      '15-19': "Social energy is very low today. You may feel disconnected or at odds with those around you. Solitude might be more comfortable than forced interaction.",
      '10-14': "Social energy is very low today. You feel disconnected or at odds with others. Betrayal or disappointment from someone is possible. Protect yourself.",
      '5-9': "A difficult day for any social matters. Serious misunderstandings or conflicts may occur. It's best to minimize social contact and focus on self-protection.",
      '0-4': "A very difficult day for social matters. Serious misunderstandings or conflicts may occur. Feelings of deep isolation or betrayal are possible. Minimize all social contact. This difficult period will pass.",
    },
  },
  ko: {
    love: {
      '95-100': "오늘 당신의 연애 에너지가 절정에 달했습니다! 우주가 사랑의 문제에 완벽하게 정렬되어 있어요. 운명적인 만남이나 사랑하는 사람과의 깊고 의미 있는 순간이 기다리고 있습니다. 일생일대의 사랑의 기회입니다. 모든 대화가 연결의 불꽃으로 빛나고, 당신의 매력은 거부할 수 없을 정도예요. 당신의 마음을 완전히 믿으세요—마음이 정확히 어디로 가야 하는지 알고 있습니다.",
      '90-94': "오늘 당신의 연애 에너지가 절정입니다! 우주가 사랑의 문제에 완벽하게 정렬되어 있어요. 운명적인 만남이나 사랑하는 사람과의 깊은 순간이 기다리고 있습니다. 모든 대화가 연결의 불꽃으로 빛나고, 당신의 매력은 거부할 수 없어요. 당신의 마음을 완전히 믿으세요.",
      '85-89': "오늘 사랑이 자연스럽게 당신에게 흘러옵니다. 감정적 직관이 높아져 다른 사람들과 더 깊은 수준에서 연결하기 쉬워요. 연인이 있다면 따뜻하고 의미 있는 대화를 기대하세요. 싱글이라면 특별한 누군가에게 끌릴 수 있습니다.",
      '80-84': "오늘 사랑이 자연스럽게 당신에게 흘러옵니다. 감정적 직관이 높아져 다른 사람들과 연결하기 쉬워요. 연인이 있다면 따뜻한 대화를 기대하세요. 싱글이라면 흥미로운 대화가 있을 수 있습니다.",
      '75-79': "오늘 부드러운 연애 에너지가 당신을 감싸고 있습니다. 폭발적이지는 않지만 연애 생활에 꾸준한 따뜻함이 있어요. 작은 애정 표현이 주목받고 감사히 여겨질 거예요. 미묘한 관심의 신호에 열린 마음을 가지세요.",
      '70-74': "오늘 부드러운 연애 에너지가 당신을 감싸고 있습니다. 관계에 꾸준한 따뜻함이 있어요. 작은 애정 표현이 주목받을 거예요. 주변 사람들에게 열린 마음을 유지하세요.",
      '65-69': "오늘 연애 생활이 편안한 균형을 유지합니다. 드라마틱한 일은 없지만 즐거운 상호작용이 있을 것 같아요. 흥분을 찾기보다 가진 것에 감사하는 데 집중하세요.",
      '60-64': "오늘 연애 생활이 편안한 균형을 유지합니다. 즐거운 상호작용이 가능해요. 작은 순간들을 감사히 여기고 사랑하는 사람과 함께하는 데 집중하세요.",
      '55-59': "오늘 로맨스는 조용한 톤을 띕니다. 연결을 강요하지 마세요—자연스럽게 전개되도록 하세요. 관계에서 진정으로 원하는 것에 대해 자기 성찰하기 좋은 날입니다.",
      '50-54': "오늘 로맨스는 조용한 톤을 띕니다. 연결을 강요하지 마세요. 관계 목표와 감정적 필요에 대해 자기 성찰하는 시간으로 활용하세요.",
      '45-49': "오늘 약간의 감정적 거리감을 느낄 수 있습니다. 소통에 추가 노력이 필요할 수 있어요. 자신과 타인에게 인내심을 가지세요—매일이 로맨틱할 필요는 없습니다.",
      '40-44': "오늘 약간의 감정적 거리감을 느낄 수 있습니다. 소통에 추가 노력이 필요해요. 인내심을 갖고 깊은 대화를 밀어붙이지 마세요. 약간의 오해가 있을 수 있습니다.",
      '35-39': "오늘 연애 에너지가 약합니다. 오해받거나 무시당하는 느낌이 들 수 있어요. 관계의 압박에서 한 발 물러나 자신의 감정적 안녕에 집중하세요.",
      '30-34': "오늘 연애 에너지가 약합니다. 오해받거나 무시당하는 느낌이 들 수 있어요. 중요한 관계 결정은 피하세요. 상호작용에서 약간의 긴장이 있을 수 있습니다.",
      '25-29': "오늘 사랑에서 도전이 있을 수 있습니다. 의사소통 오류나 단절감이 있을 것 같아요. 진지한 관계 대화는 미루고 자기 관리에 집중하는 것이 좋습니다.",
      '20-24': "오늘 사랑에서 도전이 있을 수 있습니다. 의사소통 오류나 단절감이 있을 것 같아요. 대립을 피하세요. 과거 문제가 예기치 않게 다시 떠오를 수 있습니다.",
      '15-19': "연애 문제에 어려운 날입니다. 감정이 무겁고 연결이 긴장될 수 있어요. 마음을 보호하고 관계에 대한 영구적인 결정은 피하세요.",
      '10-14': "연애 문제에 어려운 날입니다. 감정이 무겁고 연결이 긴장됩니다. 다툼이나 실망이 있을 수 있어요. 감정을 처리할 공간을 가지세요.",
      '5-9': "오늘 사랑이 멀고 도전적으로 느껴집니다. 거절이나 깊은 오해를 경험할 수 있어요. 추구가 아닌 감정 보호를 위한 날입니다. 더 좋은 날이 올 거예요.",
      '0-4': "오늘 사랑이 매우 멀게 느껴집니다. 거절이나 깊은 오해를 경험할 수 있어요. 고립이 필요하게 느껴질 수 있습니다. 오직 감정 보호만을 위한 날입니다. 이것 또한 지나갈 것임을 기억하세요.",
    },
    money: {
      '95-100': "오늘 재정 운이 찬란하게 빛납니다! 별들이 부와 번영을 위한 예외적인 기회를 나타내고 있어요. 수입의 큰 돌파구나 예상치 못한 횡재가 매우 가능합니다. 당신의 재정적 직감이 날카롭습니다—완전히 믿으세요. 대담한 재정적 움직임을 하기에 완벽한 날입니다. 오늘 내리는 모든 투자 결정이 우주적 행운의 축복을 받습니다.",
      '90-94': "오늘 재정 운이 찬란하게 빛납니다! 별들이 부와 번영을 위한 예외적인 기회를 나타내고 있어요. 수입의 큰 돌파구나 예상치 못한 횡재가 매우 가능합니다. 당신의 재정적 직감이 날카롭습니다—완전히 믿으세요. 오늘 내리는 모든 투자 결정이 축복받습니다.",
      '85-89': "오늘 금전 문제가 매우 좋아 보입니다. 재정에 대한 판단이 건전하고 이익의 기회가 있어요. 인상, 좋은 거래, 현명한 저축이든 번영이 당신에게 흘러옵니다.",
      '80-84': "오늘 금전 문제가 좋아 보입니다. 재정에 대한 판단이 건전하고 이익의 기회가 있어요. 좋은 거래나 현명한 저축 기회가 나타날 수 있습니다.",
      '75-79': "재정에 안정적이고 긍정적인 날입니다. 작은 이익이 가능하고 지출 결정이 현명할 것 같아요. 큰 위험을 감수할 날은 아니지만 꾸준한 진전은 당신의 것입니다.",
      '70-74': "재정에 안정적인 날입니다. 작은 이익이 가능하고 지출 결정이 현명할 것 같아요. 큰 위험보다 꾸준한 진전에 집중하세요.",
      '65-69': "오늘 재정 상황이 균형을 유지합니다. 큰 이익이나 손실은 예상되지 않아요—일상적인 자금 관리와 미래 계획을 세우기 좋은 날입니다.",
      '60-64': "오늘 재정 상황이 균형을 유지합니다. 일상적인 자금 관리에 좋은 날이에요. 예산을 검토하고 작은 조정을 고려하세요.",
      '55-59': "오늘 재정에 조금 더 주의가 필요합니다. 충동 구매를 피하고 예산을 지키세요. 나쁜 날은 아니지만 주의가 보상받는 날입니다.",
      '50-54': "오늘 재정에 주의가 필요합니다. 충동 구매를 피하고 예산을 지키세요. 최근 지출을 검토하고 다가오는 의무를 계획하세요.",
      '45-49': "오늘 지출에 주의하세요. 예상치 못한 비용이 생길 수 있어요. 예비금을 유지하고 돈을 빌려주거나 큰 구매를 피하세요.",
      '40-44': "오늘 지출에 주의하세요. 예상치 못한 비용이 생길 수 있어요. 예비금을 유지하고 돈을 빌려주지 마세요. 약간의 재정적 스트레스가 있을 수 있습니다.",
      '35-39': "오늘 재정적 주의가 권장됩니다. 에너지가 새로운 투자나 큰 구매를 지원하지 않아요. 성장보다 가진 것을 보존하는 데 집중하세요.",
      '30-34': "오늘 재정적 주의가 강력히 권장됩니다. 에너지가 새로운 투자를 지원하지 않아요. 예상치 못한 청구서나 손실이 있을 수 있습니다. 보존에 집중하세요.",
      '25-29': "금전 문제에 도전적인 날입니다. 지불 지연이나 예상치 못한 비용이 발생할 수 있어요. 재정적 약속을 피하고 계좌를 주의 깊게 살피세요.",
      '20-24': "금전 문제에 도전적인 날입니다. 지불 지연이나 예상치 못한 비용이 발생할 수 있어요. 재정적 불안이 증가할 수 있습니다. 불필요한 지출을 모두 피하세요.",
      '15-19': "오늘 재정적 어려움이 압박으로 느껴질 수 있습니다. 금전적 위험을 감수할 때가 아니에요. 자원을 보호하고 필요하면 조언을 구하세요.",
      '10-14': "오늘 재정적 어려움이 압박으로 느껴질 수 있습니다. 손실이나 차질이 있을 수 있어요. 자원을 주의 깊게 보호하세요. 중요한 결정에 직면하면 전문가 조언을 구하세요.",
      '5-9': "재정에 매우 어려운 날입니다. 손실이나 심각한 차질이 있을 수 있어요. 가능하면 모든 재정 결정을 피하세요. 피해 통제에 집중하세요.",
      '0-4': "재정에 매우 어려운 날입니다. 심각한 손실이나 차질이 있을 수 있어요. 모든 재정 결정을 피하세요. 오직 피해 통제만을 위한 날입니다. 신뢰할 수 있는 조언자의 도움을 구하세요.",
    },
    study: {
      '95-100': "오늘 당신의 지적 능력이 절정에 달했습니다! 지식이 마음속으로 힘들이지 않고 흘러들어오고, 복잡한 개념이 수정처럼 명확해져요. 시험이나 학업 도전이 거의 너무 쉽게 느껴질 거예요. 학습을 위한 전설적인 날입니다. 기억 유지력이 뛰어나고 창의적 통찰이 파도처럼 밀려옵니다. 학문적 탁월함을 위한 이 드문 기회를 잡으세요!",
      '90-94': "오늘 당신의 지적 능력이 절정에 달했습니다! 지식이 마음속으로 힘들이지 않고 흘러들어오고, 복잡한 개념이 수정처럼 명확해져요. 시험이나 학업 도전이 관리 가능하게 느껴질 거예요. 기억 유지력이 뛰어나고 창의적 통찰이 자연스럽게 옵니다.",
      '85-89': "공부와 정신 작업에 훌륭한 날입니다. 집중력이 강하고 정보를 잘 기억할 거예요. 시험, 발표, 또는 중요한 프로젝트가 좋은 결과를 가져올 거예요. 준비를 믿으세요.",
      '80-84': "공부와 정신 작업에 훌륭한 날입니다. 집중력이 강하고 정보를 잘 기억할 거예요. 자신감을 갖고 학업 과제에 접근하세요.",
      '75-79': "오늘 학습이 순조롭게 진행됩니다. 평소보다 집중하고 새로운 자료를 이해하기 쉬울 거예요. 피해왔던 과목을 다루기 좋은 날입니다.",
      '70-74': "오늘 학습이 순조롭게 진행됩니다. 집중하고 새로운 자료를 이해하기 쉬울 거예요. 학업 목표에서 꾸준한 진전이 있을 것 같습니다.",
      '65-69': "학업 추구에 꾸준한 날입니다. 예외적이지는 않지만 노력이 비례한 결과를 가져올 거예요. 오늘의 일관된 작업이 내일의 성공을 만듭니다.",
      '60-64': "학업 추구에 꾸준한 날입니다. 노력이 비례한 결과를 가져올 거예요. 새로운 자료보다 복습과 정리에 집중하세요.",
      '55-59': "오늘 공부에 추가 노력이 필요할 수 있습니다. 주의가 산만해지기 쉬우니 집중할 수 있는 환경을 만드세요. 짧고 집중된 공부 세션이 긴 것보다 효과적입니다.",
      '50-54': "오늘 공부에 추가 노력이 필요할 수 있습니다. 주의가 산만해지기 쉬워요. 공부 세션을 짧게 유지하고 효과를 유지하기 위해 규칙적인 휴식을 취하세요.",
      '45-49': "오늘 집중이 도전적일 수 있습니다. 가능하면 중요한 시험을 잡지 마세요. 어려운 새 개념보다 가벼운 복습에 집중하세요.",
      '40-44': "오늘 집중이 도전적일 수 있습니다. 중요한 시험을 잡지 마세요. 어려운 자료에 좌절감이 있을 것 같아요. 쉬운 작업에 집중하세요.",
      '35-39': "오늘 학업 에너지가 낮습니다. 새로운 것을 배우는 게 오르막길처럼 느껴질 거예요. 가능하면 가벼운 학습량을 주고 마음을 쉬게 하세요.",
      '30-34': "오늘 학업 에너지가 낮습니다. 학습이 오르막길처럼 느껴져요. 정신적 피로가 있을 것 같습니다. 도전적인 지적 작업은 미루는 것을 고려하세요.",
      '25-29': "지적 추구에 어려운 날입니다. 마음이 흐릿하거나 산만하게 느껴질 수 있어요. 중요한 시험이나 발표를 피하세요. 휴식과 정신적 회복에 집중하세요.",
      '20-24': "지적 추구에 어려운 날입니다. 마음이 흐릿하거나 산만하게 느껴져요. 작업에서 실수가 더 많을 것 같습니다. 중요한 모든 것을 다시 확인하세요.",
      '15-19': "오늘 정신적 명확성이 크게 손상되었습니다. 공부가 좌절스럽고 비생산적으로 느껴질 거예요. 가능하면 학업에서 휴식을 취하고 새롭게 돌아오세요.",
      '10-14': "오늘 정신적 명확성이 크게 손상되었습니다. 공부가 좌절스럽고 비생산적으로 느껴져요. 오류와 건망증이 있을 것 같습니다. 마음을 쉬게 하세요.",
      '5-9': "학습에 매우 도전적인 날입니다. 마음이 집중을 거부하고 기억 유지가 최소입니다. 학업 성취가 아닌 완전한 정신적 휴식을 위한 날입니다.",
      '0-4': "학습에 매우 도전적인 날입니다. 마음이 강하게 집중을 거부하고 기억 유지가 최소입니다. 피로나 혼란이 지배할 수 있어요. 완전한 휴식이 필수입니다. 공부하기 더 좋은 날이 올 거예요.",
    },
    social: {
      '95-100': "오늘 당신의 사교적 매력이 절대적으로 특별합니다! 사람들이 전에 없이 당신에게 끌리고, 모든 상호작용이 긍정적인 에너지로 빛나요. 네트워킹 기회가 당신의 인생을 바꿀 수 있습니다. 인연을 위한 일생일대의 날입니다. 오늘 형성된 새로운 우정이 영원히 지속될 수 있어요. 당신은 주변 모든 사람을 영감을 주고 하나로 만드는 힘이 있습니다!",
      '90-94': "오늘 당신의 사교적 매력이 절대적으로 특별합니다! 사람들이 당신에게 끌리고, 모든 상호작용이 긍정적인 에너지로 빛나요. 네트워킹 기회가 풍부합니다. 오늘 형성된 새로운 우정이 오래 지속될 수 있어요. 당신은 주변 사람들을 영감을 주는 힘이 있습니다.",
      '85-89': "오늘 사회적 상호작용이 아름답게 흐릅니다. 의사소통 능력이 향상되고 다른 사람들이 당신의 존재에 따뜻하게 반응해요. 팀 프로젝트, 회의, 또는 새 친구를 사귀기에 좋은 날입니다.",
      '80-84': "오늘 사회적 상호작용이 아름답게 흐릅니다. 의사소통 능력이 향상되고 다른 사람들이 따뜻하게 반응해요. 팀 프로젝트나 네트워크 확장에 좋은 날입니다.",
      '75-79': "오늘 다른 사람들과의 연결이 쉽게 옵니다. 공통점을 빨리 찾고 대화가 자연스럽게 느껴져요. 친구나 동료로부터의 지원이 쉽게 가능합니다.",
      '70-74': "오늘 다른 사람들과의 연결이 쉽게 옵니다. 대화가 자연스럽고 공통점을 찾을 수 있어요. 연락하려고 했던 누군가에게 연락하세요.",
      '65-69': "사교적 문제에 즐거운 날입니다. 예외적이지는 않지만 상호작용이 원활하고 협조적일 거예요. 작은 제스처로 기존 관계를 유지하세요.",
      '60-64': "사교적 문제에 즐거운 날입니다. 상호작용이 충분히 원활할 거예요. 새로운 관계를 만들기보다 기존 관계를 유지하는 데 집중하세요.",
      '55-59': "오늘 사교적 에너지가 중간 정도입니다. 일부 상호작용이 평소보다 더 많은 노력이 필요할 수 있어요. 사교적 참여를 현명하게 선택하고 과도하게 약속하지 마세요.",
      '50-54': "오늘 사교적 에너지가 중간 정도입니다. 일부 상호작용에 더 많은 노력이 필요해요. 사교적 참여에 선택적이 되고 중요한 것을 위해 에너지를 보존하세요.",
      '45-49': "오늘 사회적 상황이 약간 어색하게 느껴질 수 있습니다. 사소한 오해가 있을 수 있어요. 의사소통에서 명확하게 하고 다른 사람들에게 인내심을 가지세요.",
      '40-44': "오늘 사회적 상황이 어색하게 느껴질 수 있습니다. 사소한 오해가 있을 수 있어요. 그룹 갈등을 피하세요. 의사소통에서 특히 명확하게 하세요.",
      '35-39': "오늘 대인 관계 긴장이 생길 수 있습니다. 다른 사람들이 덜 수용적이거나 더 비판적으로 보일 수 있어요. 민감한 주제를 피하고 가능하면 상호작용을 가볍게 유지하세요.",
      '30-34': "오늘 대인 관계 긴장이 생길 수 있습니다. 다른 사람들이 덜 수용적이거나 더 비판적으로 보여요. 의견 충돌이 있을 것 같습니다. 토론을 가볍게 유지하고 논쟁을 피하세요.",
      '25-29': "관계에 도전적인 날입니다. 갈등이나 고립감이 있을 수 있어요. 사교적 참여를 제한하고 신뢰할 수 있는 지지적인 연결에만 집중하세요.",
      '20-24': "관계에 도전적인 날입니다. 갈등이나 고립감이 있을 것 같아요. 배제되거나 오해받는 느낌이 들 수 있습니다. 사회적 노출을 제한하세요.",
      '15-19': "오늘 사교적 에너지가 매우 낮습니다. 주변 사람들과 단절되거나 불화를 느낄 수 있어요. 강제된 상호작용보다 고독이 더 편안할 수 있습니다.",
      '10-14': "오늘 사교적 에너지가 매우 낮습니다. 다른 사람들과 단절되거나 불화를 느껴요. 누군가로부터 배신이나 실망이 있을 수 있습니다. 자신을 보호하세요.",
      '5-9': "모든 사교적 문제에 어려운 날입니다. 심각한 오해나 갈등이 발생할 수 있어요. 사회적 접촉을 최소화하고 자기 보호에 집중하는 것이 좋습니다.",
      '0-4': "사교적 문제에 매우 어려운 날입니다. 심각한 오해나 갈등이 발생할 수 있어요. 깊은 고립감이나 배신감이 있을 수 있습니다. 모든 사회적 접촉을 최소화하세요. 이 어려운 시기는 지나갈 거예요.",
    },
  },
};

// 점수 구간별 조언
export const scoreAdvices: Record<Locale, Record<ScoreRange, string>> = {
  en: {
    '95-100': "Seize every opportunity that comes your way today. Fortune favors the bold, and you are unstoppable!",
    '90-94': "Take confident action on your goals. The stars strongly support your endeavors today.",
    '85-89': "Move forward with your plans. Conditions are very favorable for progress.",
    '80-84': "A great day to pursue your objectives. Trust your judgment and take positive steps.",
    '75-79': "Continue on your current path with optimism. Good things are developing.",
    '70-74': "Stay the course and maintain your efforts. Steady progress is yours.",
    '65-69': "Keep up your routine and stay open to small opportunities.",
    '60-64': "Focus on consistency. Small, steady efforts will accumulate.",
    '55-59': "Proceed with mild caution but don't hold back entirely.",
    '50-54': "Balance action with reflection. Neither rush nor delay.",
    '45-49': "Be a bit more careful than usual in your decisions.",
    '40-44': "Exercise caution and avoid unnecessary risks today.",
    '35-39': "Take a conservative approach. Protect what you have.",
    '30-34': "Minimize risk-taking and focus on stability.",
    '25-29': "Be very careful with decisions. Seek advice if needed.",
    '20-24': "Avoid major decisions if possible. Focus on self-care.",
    '15-19': "Lay low and let this difficult energy pass.",
    '10-14': "Prioritize self-protection and basic needs only.",
    '5-9': "This is a day for rest and recovery, nothing more.",
    '0-4': "Focus only on getting through today. Tomorrow will be better.",
  },
  ko: {
    '95-100': "오늘 다가오는 모든 기회를 잡으세요. 행운은 대담한 자의 편이고, 당신은 멈출 수 없습니다!",
    '90-94': "목표에 대해 자신감 있게 행동하세요. 별들이 오늘 당신의 노력을 강력히 지지합니다.",
    '85-89': "계획을 추진하세요. 진전을 위한 조건이 매우 유리합니다.",
    '80-84': "목표를 추구하기에 좋은 날입니다. 판단을 믿고 긍정적인 조치를 취하세요.",
    '75-79': "낙관적으로 현재 경로를 계속하세요. 좋은 일들이 전개되고 있습니다.",
    '70-74': "경로를 유지하고 노력을 계속하세요. 꾸준한 진전이 당신의 것입니다.",
    '65-69': "일상을 유지하고 작은 기회에 열려 있으세요.",
    '60-64': "일관성에 집중하세요. 작고 꾸준한 노력이 쌓일 거예요.",
    '55-59': "약간의 주의를 기울이되 완전히 주저하지는 마세요.",
    '50-54': "행동과 성찰의 균형을 맞추세요. 서두르지도 지체하지도 마세요.",
    '45-49': "결정에서 평소보다 조금 더 주의하세요.",
    '40-44': "주의를 기울이고 오늘 불필요한 위험을 피하세요.",
    '35-39': "보수적인 접근을 취하세요. 가진 것을 보호하세요.",
    '30-34': "위험 감수를 최소화하고 안정에 집중하세요.",
    '25-29': "결정에 매우 주의하세요. 필요하면 조언을 구하세요.",
    '20-24': "가능하면 중요한 결정을 피하세요. 자기 관리에 집중하세요.",
    '15-19': "조용히 있고 이 어려운 에너지가 지나가게 하세요.",
    '10-14': "자기 보호와 기본적인 필요에만 우선순위를 두세요.",
    '5-9': "휴식과 회복을 위한 날입니다, 그 이상은 없어요.",
    '0-4': "오늘을 버티는 데만 집중하세요. 내일은 더 나을 거예요.",
  },
};

// 점수 구간별 주의사항
export const scoreCautions: Record<Locale, Record<ScoreRange, string>> = {
  en: {
    '95-100': "Don't let overconfidence lead to carelessness. Stay grounded even at the peak.",
    '90-94': "Remember that good fortune requires good stewardship. Stay humble.",
    '85-89': "Avoid taking your good luck for granted. Appreciate and nurture it.",
    '80-84': "Watch for small oversights that could undermine your progress.",
    '75-79': "Don't expect perfection. Appreciate the good while accepting minor setbacks.",
    '70-74': "Stay alert to details you might overlook when things are going well.",
    '65-69': "Avoid complacency. Maintain your efforts even without dramatic results.",
    '60-64': "Don't compare yourself to others. Focus on your own steady journey.",
    '55-59': "Watch for minor frustrations that could affect your mood.",
    '50-54': "Avoid both pessimism and unrealistic optimism. Stay balanced.",
    '45-49': "Be careful not to let small setbacks discourage you too much.",
    '40-44': "Don't make important decisions based on today's challenging energy.",
    '35-39': "Avoid conflicts and confrontations. They won't end well today.",
    '30-34': "Be wary of people or situations that drain your energy.",
    '25-29': "Protect yourself from negativity, both internal and external.",
    '20-24': "Avoid isolation but also avoid toxic interactions.",
    '15-19': "Don't make any permanent decisions during this temporary difficulty.",
    '10-14': "Be very gentle with yourself. Avoid self-criticism.",
    '5-9': "Seek support if needed. You don't have to face difficulties alone.",
    '0-4': "Remember: this is temporary. Don't let today define your tomorrow.",
  },
  ko: {
    '95-100': "과신이 부주의로 이어지지 않게 하세요. 정점에서도 겸손을 유지하세요.",
    '90-94': "좋은 운은 좋은 관리가 필요함을 기억하세요. 겸손하세요.",
    '85-89': "좋은 운을 당연하게 여기지 마세요. 감사하고 가꾸세요.",
    '80-84': "진전을 저해할 수 있는 작은 실수를 주의하세요.",
    '75-79': "완벽을 기대하지 마세요. 작은 차질을 받아들이면서 좋은 것을 감사하세요.",
    '70-74': "일이 잘 될 때 놓칠 수 있는 세부사항에 주의하세요.",
    '65-69': "안주하지 마세요. 극적인 결과 없이도 노력을 유지하세요.",
    '60-64': "자신을 다른 사람과 비교하지 마세요. 자신만의 꾸준한 여정에 집중하세요.",
    '55-59': "기분에 영향을 줄 수 있는 사소한 좌절에 주의하세요.",
    '50-54': "비관주의와 비현실적 낙관주의 둘 다 피하세요. 균형을 유지하세요.",
    '45-49': "작은 차질이 너무 낙담시키지 않게 주의하세요.",
    '40-44': "오늘의 도전적인 에너지에 기반해 중요한 결정을 내리지 마세요.",
    '35-39': "갈등과 대립을 피하세요. 오늘은 잘 끝나지 않을 거예요.",
    '30-34': "에너지를 빼앗는 사람이나 상황을 경계하세요.",
    '25-29': "내부와 외부의 부정적인 것으로부터 자신을 보호하세요.",
    '20-24': "고립을 피하되 독성 있는 상호작용도 피하세요.",
    '15-19': "이 일시적인 어려움 동안 영구적인 결정을 내리지 마세요.",
    '10-14': "자신에게 매우 부드럽게 대하세요. 자기 비판을 피하세요.",
    '5-9': "필요하면 도움을 구하세요. 어려움을 혼자 직면할 필요 없어요.",
    '0-4': "기억하세요: 이것은 일시적입니다. 오늘이 내일을 정의하게 하지 마세요.",
  },
};

// 점수 구간별 태그
export const scoreTags: Record<Locale, Record<ScoreRange, string[]>> = {
  en: {
    '95-100': ['#Blessed', '#PeakFortune', '#Unstoppable', '#CosmicAlignment'],
    '90-94': ['#Fortunate', '#HighEnergy', '#Thriving', '#StarPower'],
    '85-89': ['#VeryGood', '#Flowing', '#Positive', '#OnTrack'],
    '80-84': ['#Good', '#Favorable', '#Progressing', '#Confident'],
    '75-79': ['#Promising', '#Steady', '#Hopeful', '#Growing'],
    '70-74': ['#Stable', '#Decent', '#Calm', '#Balanced'],
    '65-69': ['#Okay', '#Neutral', '#Maintaining', '#Routine'],
    '60-64': ['#Average', '#Normal', '#Holding', '#Patience'],
    '55-59': ['#Careful', '#Watchful', '#Cautious', '#Aware'],
    '50-54': ['#Mixed', '#Variable', '#Uncertain', '#Waiting'],
    '45-49': ['#Challenging', '#Mindful', '#Alert', '#Guarded'],
    '40-44': ['#Difficult', '#Tough', '#Struggling', '#Enduring'],
    '35-39': ['#Hard', '#Testing', '#Preserving', '#Surviving'],
    '30-34': ['#VeryHard', '#Stormy', '#Protecting', '#Weathering'],
    '25-29': ['#Crisis', '#Retreat', '#SelfCare', '#Healing'],
    '20-24': ['#Hardship', '#Shelter', '#Rest', '#Recovery'],
    '15-19': ['#Darkness', '#Waiting', '#Hope', '#Strength'],
    '10-14': ['#Storm', '#Endurance', '#Faith', '#Tomorrow'],
    '5-9': ['#Trial', '#Survival', '#Courage', '#Dawn'],
    '0-4': ['#DeepNight', '#HoldOn', '#ThisTooShallPass', '#NewBeginning'],
  },
  ko: {
    '95-100': ['#축복', '#최고운', '#무적', '#우주정렬'],
    '90-94': ['#행운', '#고에너지', '#번창', '#별의힘'],
    '85-89': ['#아주좋음', '#순조로움', '#긍정적', '#순항중'],
    '80-84': ['#좋음', '#유리함', '#진전중', '#자신감'],
    '75-79': ['#유망함', '#안정적', '#희망적', '#성장중'],
    '70-74': ['#안정', '#양호', '#평온', '#균형'],
    '65-69': ['#괜찮음', '#중립', '#유지중', '#일상'],
    '60-64': ['#평균', '#보통', '#버티기', '#인내'],
    '55-59': ['#조심', '#경계', '#신중', '#주의'],
    '50-54': ['#혼합', '#변동', '#불확실', '#대기'],
    '45-49': ['#도전', '#마음챙김', '#경보', '#방어'],
    '40-44': ['#어려움', '#힘듦', '#분투', '#인내'],
    '35-39': ['#고됨', '#시험', '#보존', '#생존'],
    '30-34': ['#매우힘듦', '#폭풍', '#보호', '#극복중'],
    '25-29': ['#위기', '#후퇴', '#자기관리', '#치유'],
    '20-24': ['#고난', '#피난처', '#휴식', '#회복'],
    '15-19': ['#어둠', '#기다림', '#희망', '#힘'],
    '10-14': ['#폭풍', '#인내', '#믿음', '#내일'],
    '5-9': ['#시련', '#생존', '#용기', '#새벽'],
    '0-4': ['#깊은밤', '#버티기', '#이또한지나가리', '#새로운시작'],
  },
};

// 등급 라벨 (UI 표시용)
export const gradeLabels: Record<ScoreRange, { en: string; kr: string }> = {
  '95-100': { en: 'Legendary Fortune', kr: '전설의 운' },
  '90-94': { en: 'Exceptional Fortune', kr: '최상의 운' },
  '85-89': { en: 'Excellent Fortune', kr: '아주 좋은 운' },
  '80-84': { en: 'Great Fortune', kr: '좋은 운' },
  '75-79': { en: 'Good Fortune', kr: '괜찮은 운' },
  '70-74': { en: 'Favorable Fortune', kr: '무난한 운' },
  '65-69': { en: 'Fair Fortune', kr: '평균 이상' },
  '60-64': { en: 'Average Fortune', kr: '평균' },
  '55-59': { en: 'Mixed Fortune', kr: '평균 이하' },
  '50-54': { en: 'Uncertain Fortune', kr: '불확실' },
  '45-49': { en: 'Challenging Fortune', kr: '도전적' },
  '40-44': { en: 'Difficult Fortune', kr: '어려움' },
  '35-39': { en: 'Hard Fortune', kr: '힘듦' },
  '30-34': { en: 'Very Hard Fortune', kr: '매우 힘듦' },
  '25-29': { en: 'Troubled Fortune', kr: '시련' },
  '20-24': { en: 'Crisis Fortune', kr: '위기' },
  '15-19': { en: 'Dark Fortune', kr: '암흑기' },
  '10-14': { en: 'Stormy Fortune', kr: '폭풍' },
  '5-9': { en: 'Severe Fortune', kr: '극한' },
  '0-4': { en: 'Rock Bottom', kr: '최악' },
};
